version: '2.2'

services:
  api:
    expose:
      - 8000
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: '/static/'
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    depends_on:
      - db
      - redis
    volumes:
      - ./saleor/:/app/saleor:Z
      - ./templates/:/app/templates:Z
      - ./tests/:/app/tests
      # prevents overshadowing of build-time assets
      #- /app/saleor/static/assets
      - ./webpack-bundle.json:/app/webpack-bundle.json:Z
      #- /app/templates/templated_email/compiled
      # shared volume between worker and api for media
      - saleor-media:/app/media
    command: gunicorn saleor.wsgi:application --bind 0.0.0.0:8000
    env_file: ./common.prod.env
    environment:
      - STOREFRONT_URL=http://3.132.182.123/
      - DASHBOARD_URL=http://3.132.182.123/dashboard

  db:
    image: library/postgres:11.1-alpine
    expose:
      - 5432
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-db:/var/lib/postgresql
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor
      
  redis:
    image: library/redis:5.0-alpine
    expose:
      - 6379
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-redis:/data

  worker:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: '/static/'
    command: celery -A saleor worker --app=saleor.celeryconf:app --loglevel=info
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    env_file: ./common.prod.env
    depends_on:
      - redis
    volumes:
      - ./saleor/:/app/saleor:Z
      - ./templates/:/app/templates:Z
      - ./tests/:/app/tests
      # prevents overshadowing of build-time assets
      #- /app/saleor/static/assets
      - ./webpack-bundle.json:/app/webpack-bundle.json:Z
      #- /app/templates/templated_email/compiled
      # shared volume between worker and api for media
      - saleor-media:/app/media

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    volumes:
      - saleor-media:/app/media
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:Z
      - ./app:/home/appz:Z
    ports:
      - 80:80
    links:
      - api:api
    depends_on:
      - api
    networks:
      - saleor-backend-tier

volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local
  saleor-media:

networks:
  saleor-backend-tier:
    driver: bridge
